### ISSUE TITLE
Should I copy the whitesource configuration to my project?

### ISSUE THREAD

**Issue by petyosi** [finos/project-blueprint#12]
## Support Question

Thank you very much for the effort put in this blueprint! It helps tremendously with the new setup. Something which is left unclear (to me at least) is the usage of the whitesource configuration files. They are present in the repo, but not mentioned in the README. What would be the recommended way to use them? 

Thanks!

**Comment by maoo** [comment]
Hi @petyosi , I'm glad to hear this project helped you! In order to enable WhiteSource for your project, first step is to email help@finos.org with your repository coordinates, so we can enable the integration on our end.

I'd suggest to first test the integration with the automatic setup, defined by the bot, and then use a custom configuration, as shown here. I'm also adding this to our GitHub docs - https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530554/Code+Hosting

Thanks!

**Comment by mcleo-d** [comment]
🙌🏻 💯💯💯

**Comment by mcleo-d** [comment]
Great to see you here @petyosi 😀

**Comment by mcleo-d** [comment]
Hi @petyosi

I hope you and the team are well? 

Please let us know the repo where you'd WhiteSource enabled and we'll work with you to enable and configure.

James.

**Comment by petyosi** [comment]
My question relates to our recent initiative which we presented at the January meetups. At some point, we can bring the project to the attention of FINOS; However, our initial setup will be within our own Github organization. 

Given that, I guess that we can't take advantage of the WhiteSource integration. Let me know if this is not the case. Thank you!

**Comment by maoo** [comment]
You definitely can, but you must follow https://whitesource.atlassian.net/wiki/spaces/WD/pages/697696422/WhiteSource+for+GitHub.com directly.

If you have any questions, you can hop on one of [our bi-weekly ODP calls](https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/243859459/Open+Developer+Platform+Project#OpenDeveloperPlatformProject-ODPProjectmeeting) and meet WhiteSource there.

You'll see meeting agendas showing up on https://github.com/finos/open-developer-platform/issues , so you'll be able to post your questions/suggestions there.

Closing the ticket, thank you!
